### ISSUE TITLE
Open wikipedia.org links in WikiReader

### ISSUE THREAD

**Issue by Cwpute** [nsh07/WikiReader#12]
When i'm regularly browsing using my internet browser app, i'd like WikiReader to catch whenever i open a link on `wikipedia.org` and open it in the app instead.

**Comment by nsh07** [comment]
Will implement after  I implement some other features

**Comment by nsh07** [comment]
After a bit of research, it seems implementing this might simply be impossible. Adding an app as a link handler is really simple, but since Android 12, an Android app must be verified (i.e. be listed on a "well-known" list) by the *host domain* of the URL it is trying to open. You can see Wikipedia's official app listed on their site's "well-known" list [here](https://wikipedia.org/.well-known/assetlinks.json)

Since I do not own Wikipedia, this is completely out of question, and it is higly unlikely they'll add my app to their trusted apps list.

I'm closing this issue now, but you can reopen it if you find a solution or a workaround

**Comment by Cwpute** [comment]
I am indeed using Android 11, but these apps are supposed to work for Android 14 ! i am quite surprized NewPipe doesn't catch the links

**Comment by nsh07** [comment]
That's what I was saying, it used to work before Android 12 but doesn't anymore, sadly :(

I guess I will reopen this issue to implement a similar feature: the ability to share a Wikipedia link to this app to open it

**Comment by target6404** [comment]
> After a bit of research, it seems implementing this might simply be impossible. Adding an app as a link handler is really simple, but since Android 12, an Android app [must be verified]

This is incorrect. Verified apps are prioritized, but if no app is verified to open a link or all such apps have the 'Open supported links' setting disabled, the user can manually set an unverified app to handle these links.

**Comment by nsh07** [comment]
> Verified apps are prioritized, but if no app is verified to open a link or all such apps have the 'Open supported links' setting disabled, the user can manually set an unverified app to handle these links.

I am aware of this fact, and I only discovered it when I was trying to implement this feature, but I didn't see it as viable because many users might not know how to manually enable the app in settings

But I might implement this anyway, and maybe put some instructions in the app's description

**Comment by nsh07** [comment]
Implemented in v1.8.1
