### ISSUE TITLE
Option to change theme

### ISSUE THREAD

**Issue by shuvashish76** [nsh07/WikiReader#15]
Feature request to change the app theme
- Dark theme
- Light theme
- [Catppuccin](https://github.com/catppuccin/catppuccin) themes
- [Dracula](https://github.com/dracula/dracula-theme) theme (an interesting option but I don't prefer high-contrast colors)
- Follow system

**Comment by nsh07** [comment]
Will implement

**Comment by nsh07** [comment]
I would not be able to implement Catppuccin/Dracula/any other custom theme to make the app look and feel native (and for my own sanity: because implementing two of these themes would bombard me with more such theme requests)

However, you would be able to choose between light, dark and system default

**Comment by shuvashish76** [comment]
Makes sense. Thank you

**Comment by nsh07** [comment]
Implemented in v1.6.1

**Comment by nsh07** [comment]
Hey, I will be adding a theme picker to the app. See #21
