### ISSUE TITLE
LaTeX/KaTeX support

### ISSUE THREAD

**Issue by ThatOneCalculator** [nsh07/WikiReader#24]
Many articles appear broken due to the lack of *TeX rendering

**Comment by nsh07** [comment]
I will have to look into it. Parsing the expressions seems a bit complicated at first because it seems the wikipedia API query I'm using doesn't really return proper LaTeX-formatted expressions (it uses Wikipedia's web format for LaTeX). I might implement this, but I do agree that pages with equations look utterly broken right now.

For a quick fix, I can remove the unnecessary blank lines, which I will implement in the next release

**Comment by nsh07** [comment]
Hey, it might actually be quite easy to implement this! I've found a web server that can render LaTeX expressions into SVG images, which I can then load into articles instead of the raw latex expressions. [Here's an example](https://latex.codecogs.com/svg.latex?x&space;=&space;\frac{4}{5}+\pi\Omega\int_{2\pi}^{\infty}{5\left\(\frac{\tau+3}{2}\right\)d\omega})

**Comment by ThatOneCalculator** [comment]
Wow, that's actually awesome!! Saving that site for later

**Comment by ThatOneCalculator** [comment]
Nice! Since that's a paid product, maybe a self-hosted server could be used with smth like https://github.com/UST-QuAntiL/latex-renderer ?

**Comment by nsh07** [comment]
Actually only the web editor interface seems to be paid, the actual service seems to be completely free because the website renders the image for whatever LaTeX expression you give it without any API keys

**Comment by nsh07** [comment]
I've added support for rendering expressions. Only thing left to do is to scale the image properly on different display sizes. I will complete it tomorrow :)

<img src="https://github.com/user-attachments/assets/1ac2590d-abd6-4ade-a41f-9656333eec41" width="50%">
