### ISSUE TITLE
Support other MediaWiki wikis

### ISSUE THREAD

**Issue by Glacier7975** [nsh07/WikiReader#36]
WikiReader should support other MediaWiki wikis. This can either be a predefined list, the ability for users to add a wiki themselves or a combination of both. This would improve the experience on mobile devices for wikis that are not optimized for mobile.

**Comment by nsh07** [comment]
I will not implement this because of several reasons:

1. This is out of scope for this application. 
2. It will require quite a bit of time and effort to implement, since the format of data between different Wikis varies greatly and the UI of this app may not suit other Wikis as well as it suits Wikipedia
3. This app is intended for reading, and other MediaWiki sites aren't as text-centric as Wikipedia (with some exceptions like Wiktionary)

**Comment by nsh07** [comment]
If you still think there's a reason to implement this, feel free to reopen this issue

**Comment by ildar** [comment]
+1 to the request

**Comment by nsh07** [comment]
I might think about this later, but it is currently not on my bucket list since adding other mediawiki wikis will also require a redesign of the UI to accomodate other Wikis. I will think about this after [v2.0.0](https://github.com/users/nsh07/projects/1) is complete
