### ISSUE TITLE
Add support for android Nougat and android marshmallow and android lollipop.

### ISSUE THREAD

**Issue by OmarNazzal150** [nsh07/WikiReader#47]

**Comment by nsh07** [comment]
Do you use a device that has Android 5/6/7 or is this just a general request? Just curious to know, because I'll have to do a bit of work to make the app work with Android 5/6/7.

According to Google's statistics (As of May 2024), Android 4.4 (Kitkat) to Android 7.1 (Nougat) have a combined market share of 4.6%, and it would've shrunk even further by now

![image](https://github.com/user-attachments/assets/ffa41acf-6732-4b8a-b132-2caf3a6d5e86)

**Comment by OmarNazzal150** [comment]
It's just a general request

**Comment by nsh07** [comment]
I don't think I will add support for these extremely old Android versions unless a user who actually does use these versions requests it, because *very* few people (<4.6%) actually use a phone that has these Android versions.

To add support for these, I will have to add many different icon sizes for older android versions which will unnecessarily increase the APK's size, which is undesirable for people with newer android versions. I hope you understand.

Thanks for using my app btw! :)
